

export const awardsData = [
  {
    year: "2022",
    className: "text-start",
    direction: "left",
    awards: [
      { id: 1, image: "/images/22/IMG-20250919-WA0028.jpg", title: "Project Awardee", user: "Belinda", age: 49, country: "Germany" },
      { id: 2, image: "/images/22/IMG-20250919-WA0029.jpg", title: "Project Awardee", user: "Emily", age: 50, country: "Spain" },
      { id: 3, image: "/images/22/IMG-20250919-WA0030.jpg", title: "Project Awardee", user: "Pat", age: 48, country: "America" },
      { id: 4, image: "/images/22/IMG-20250919-WA0031.jpg", title: "Project Awardee", user: "Colleen", age: 52, country: "America" },
      { id: 5, image: "/images/22/IMG-20250919-WA0032.jpg", title: "Project Awardee", user: "Donna", age: 50, country: "Spain" },
      { id: 6, image: "/images/22/IMG-20250919-WA0033.jpg", title: "Project Awardee", user: "Kathy", age: 55, country: "Canada" },
      { id: 7, image: "/images/22/IMG-20250919-WA0034.jpg", title: "Project Awardee", user: "Patsy", age: 49, country: "Mexico" },
      { id: 8, image: "/images/22/IMG-20250919-WA0035.jpg", title: "Project Awardee", user: "Anna", age: 51, country: "Canada" },
      { id: 9, image: "/images/22/IMG-20250919-WA0036.jpg", title: "Project Awardee", user: "Linda", age: 55, country: "Germany" },
    ],
  },
  {
    year: "2023",
    className: "text-end",
    direction: "right",
    awards: [
      { id: 1, image: "/images/placeholder.png", title: "Project Awardee", user: "Donna", age: 52, country: "Brazil" },
      { id: 2, image: "/images/placeholder.png", title: "Project Awardee", user: "Patricia", age: 50, country: "Spain" },
      { id: 3, image: "/images/placeholder.png", title: "Project Awardee", user: "Barbara", age: 52, country: "Spain" },
      { id: 4, image: "/images/placeholder.png", title: "Project Awardee", user: "Lisa", age: 44, country: "Mexico" },
      { id: 5, image: "/images/placeholder.png", title: "Project Awardee", user: "Sharon", age: 49, country: "Mexico" },
      { id: 6, image: "/images/placeholder.png", title: "Project Awardee", user: "Deborah", age: 40, country: "Spain" },
      { id: 7, image: "/images/placeholder.png", title: "Project Awardee", user: "Shirley", age: 41, country: "America" },
      { id: 8, image: "/images/placeholder.png", title: "Project Awardee", user: "Amy", age: 49, country: "America" },
      { id: 9, image: "/images/placeholder.png", title: "Project Awardee", user: "Brenda", age: 50, country: "Germany" },
    ],
  },
  {
    year: "2024",
    className: "text-start",
    direction: "left",
    awards: [
      { id: 1, image: "/images/25/IMG-20250920-WA0014.jpg", title: "Project Awardee", user: "Rhoda", age: 51, country: "Mexico" },
      { id: 2, image: "/images/placeholder.png", title: "Project Awardee", user: "Virgie", age: 49, country: "Brazil" },
      { id: 3, image: "/images/placeholder.png", title: "Project Awardee", user: "Leann", age: 39, country: "Brazil" },
      { id: 4, image: "/images/placeholder.png", title: "Project Awardee", user: "Haley", age: 40, country: "Canada" },
      { id: 5, image: "/images/placeholder.png", title: "Project Awardee", user: "Sadie", age: 55, country: "Canada" },
      { id: 6, image: "/images/placeholder.png", title: "Project Awardee", user: "Brooke", age: 39, country: "America" },
      { id: 7, image: "/images/placeholder.png", title: "Project Awardee", user: "Nichole", age: 42, country: "Mexico" },
      { id: 8, image: "/images/placeholder.png", title: "Project Awardee", user: "Dianna", age: 48, country: "Mexico" },
      { id: 9, image: "/images/placeholder.png", title: "Project Awardee", user: "Luz", age: 51, country: "India" },
      { id: 10, image: "/images/placeholder.png", title: "Project Awardee", user: "Yvette", age: 48, country: "Germany" },
      { id: 11, image: "/images/placeholder.png", title: "Project Awardee", user: "Olivia", age: 49, country: "Brazil" },
      { id: 12, image: "/images/placeholder.png", title: "Project Awardee", user: "Sonya", age: 51, country: "Canada" },
    ],
  },
  {
    year: "2025",
    className: "text-end",
    direction: "right",
    awards: [
      { id: 1, image: "/images/25/IMG-20250920-WA0000.jpg", title: "Project Awardee", user: "Mary", age: 52, country: "Brazil" },
      { id: 2, image: "/images/25/IMG-20250920-WA0001.jpg", title: "Project Awardee", user: "Robin", age: 52, country: "Brazil" },
      { id: 3, image: "/images/25/IMG-20250920-WA0002.jpg", title: "Project Awardee", user: "Marion", age: 52, country: "Brazil" },
      { id: 4, image: "/images/25/IMG-20250920-WA0003.jpg", title: "Project Awardee", user: "Lilly", age: 44, country: "Mexico" },
      { id: 5, image: "/images/25/IMG-20250920-WA0004.jpg", title: "Project Awardee", user: "Mia", age: 49, country: "Canada" },
      { id: 6, image: "/images/25/IMG-20250920-WA0005.jpg", title: "Project Awardee", user: "Ava", age: 40, country: "America" },
      { id: 7, image: "/images/25/IMG-20250920-WA0006.jpg", title: "Project Awardee", user: "Tia", age: 41, country: "Spain" },
      { id: 8, image: "/images/25/IMG-20250920-WA0007.jpg", title: "Project Awardee", user: "Rae", age: 49, country: "Mexico" },
      { id: 9, image: "/images/25/IMG-20250920-WA0008.jpg", title: "Project Awardee", user: "Ines", age: 50, country: "Germany" },
      { id: 10, image: "/images/25/IMG-20250920-WA0009.jpg", title: "Project Awardee", user: "Kitty", age: 49, country: "Canada" },
      { id: 11, image: "/images/25/IMG-20250920-WA0010.jpg", title: "Project Awardee", user: "Celina", age: 52, country: "Brazil" },
      { id: 12, image: "/images/25/IMG-20250920-WA0011.jpg", title: "Project Awardee", user: "Enid", age: 44, country: "Spain" },
      { id: 13, image: "/images/25/IMG-20250920-WA0012.jpg", title: "Project Awardee", user: "Mara", age: 49, country: "Germany" },
      { id: 14, image: "/images/25/IMG-20250920-WA0013.jpg", title: "Project Awardee", user: "Sasha", age: 52, country: "Germany" },
    ],
  },
];
