// app/layout.tsx or app/layout.js
import type { Metadata } from "next";
import {
  Nunito,
  Instrument_Serif,
} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// ✅ Nunito as default font
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  variable: "--font-instrument-serif",
  display: "swap",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} ${instrumentSerif.variable}`}>
      <body className="font-nunito antialiased">
        <Toaster position="top-right" />
        {children}
      </body>
    </html>
  );
}
